# coding: utf-8

"""
    Car Rental System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_create_car_cars_post(self) -> None:
        """Test case for create_car_cars_post

        Create Car
        """
        pass

    def test_delete_rental_rentals_rental_id_delete(self) -> None:
        """Test case for delete_rental_rentals_rental_id_delete

        Delete Rental
        """
        pass

    def test_get_car_cars_car_id_get(self) -> None:
        """Test case for get_car_cars_car_id_get

        Get Car
        """
        pass

    def test_get_rental_for_car_rentals_car_car_id_get(self) -> None:
        """Test case for get_rental_for_car_rentals_car_car_id_get

        Get Rental For Car
        """
        pass

    def test_list_cars_cars_get(self) -> None:
        """Test case for list_cars_cars_get

        List Cars
        """
        pass

    def test_rent_car_cars_car_id_rent_post(self) -> None:
        """Test case for rent_car_cars_car_id_rent_post

        Rent Car
        """
        pass


if __name__ == '__main__':
    unittest.main()
