# coding: utf-8

"""
    Car Rental System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.car_out import CarOut

class TestCarOut(unittest.TestCase):
    """CarOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CarOut:
        """Test CarOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CarOut`
        """
        model = CarOut()
        if include_optional:
            return CarOut(
                make = '',
                model = '',
                year = 56,
                daily_rate = 1.337,
                id = 56,
                available = True
            )
        else:
            return CarOut(
                make = '',
                model = '',
                year = 56,
                daily_rate = 1.337,
                id = 56,
                available = True,
        )
        """

    def testCarOut(self):
        """Test CarOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
